package telran.accounting.api;

public enum AccountingCodes {
	OK, ACCOUNT_ALREADY_EXISTS, ALREADY_REVOKED, ACCOUNT_NOT_EXISTS, WRONG_PASSWORD, ALREADY_ACTIVATED,
	ROLE_ALREADY_EXISTS, ROLE_NOT_EXISTS
}
